drop table if exists books cascade ;
drop table if exists borroweditems cascade ;
drop table if exists borroweditems_user cascade ;
drop table if exists employees cascade ;
drop table if exists employees_employees cascade ;
drop table if exists employees_libraries cascade ;
drop table if exists employees_trainings cascade ;
drop table if exists libraries cascade ;
drop table if exists libraries_borrowed_items cascade ;
drop table if exists librarybooks cascade ;
drop table if exists librarybooks_borrowed_items cascade ;
drop table if exists librarymovies cascade ;
drop table if exists memberships cascade ;
drop table if exists phonenumbers cascade ;
drop table if exists socialsecuritynumbers cascade ;
drop table if exists training cascade ;
drop table if exists users cascade ;
drop table if exists users_currently_borrowed cascade ;
drop table if exists users_memberships cascade ;
drop sequence if exists books_seq;
drop sequence if exists borroweditems_seq;
drop sequence if exists libraries_seq;
drop sequence if exists librarybooks_seq;
drop sequence if exists librarymovies_seq;
drop sequence if exists person_seq;
drop sequence if exists phonenumbers_seq;
drop sequence if exists socialsecuritynumbers_seq;
drop table if exists books cascade ;
drop table if exists borroweditems cascade ;
drop table if exists borroweditems_user cascade ;
drop table if exists employees cascade ;
drop table if exists employees_employees cascade ;
drop table if exists employees_libraries cascade ;
drop table if exists employees_trainings cascade ;
drop table if exists libraries cascade ;
drop table if exists libraries_borrowed_items cascade ;
drop table if exists librarybooks cascade ;
drop table if exists librarybooks_borrowed_items cascade ;
drop table if exists librarymovies cascade ;
drop table if exists memberships cascade ;
drop table if exists phonenumbers cascade ;
drop table if exists socialsecuritynumbers cascade ;
drop table if exists training cascade ;
drop table if exists users cascade ;
drop table if exists users_currently_borrowed cascade ;
drop table if exists users_memberships cascade ;
drop sequence if exists books_seq;
drop sequence if exists borroweditems_seq;
drop sequence if exists libraries_seq;
drop sequence if exists librarybooks_seq;
drop sequence if exists librarymovies_seq;
drop sequence if exists person_seq;
drop sequence if exists phonenumbers_seq;
drop sequence if exists socialsecuritynumbers_seq;
